=== trondarild/tarot-deck/data/schemas/decks.dtd
<!ELEMENT decks (deck+)>

<!ELEMENT deck (name, description?, created?, cardCount, structure, metadata, locales, images?)>
<!ATTLIST deck
  id ID #REQUIRED
  type (tarot|playing-cards|oracle) #REQUIRED
  version CDATA #IMPLIED>

<!ELEMENT name (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT created (#PCDATA)>
<!ELEMENT cardCount (#PCDATA)>

<!ELEMENT structure EMPTY>
<!ATTLIST structure href CDATA #REQUIRED>

<!ELEMENT metadata EMPTY>
<!ATTLIST metadata href CDATA #REQUIRED>

<!ELEMENT locales (locale+)>
<!ELEMENT locale EMPTY>
<!ATTLIST locale
  lang CDATA #REQUIRED
  href CDATA #REQUIRED>

<!ELEMENT images EMPTY>
<!ATTLIST images basePath CDATA #REQUIRED>

=== trondarild/tarot-deck/data/decks.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE decks SYSTEM "schemas/decks.dtd">
<decks>
  <deck id="rws-tarot" type="tarot" version="1.0">
    <name>Waite-Smith Deck</name>
    <description>Tarot deck by A.E. Waite and Pamela Colman Smith</description>
    <created>1909</created>
    <cardCount>78</cardCount>
    <structure href="decks/rws-tarot/structure.xml"/>
    <metadata href="decks/rws-tarot/metadata.xml"/>
    <locales>
      <locale lang="en" href="decks/rws-tarot/locales/deck.en.xml"/>
      <locale lang="uk" href="decks/rws-tarot/locales/deck.uk.xml"/>
    </locales>
    <images basePath="assets/img/big/"/>
  </deck>

  <deck id="standard-playing" type="playing-cards" version="1.0" status="draft">
    <name>Standard Playing Cards</name>
    <description>52-card French-suited deck</description>
    <cardCount>52</cardCount>
    <structure href="decks/standard-playing/structure.xml"/>
    <metadata href="decks/standard-playing/metadata.xml"/>
    <locales>
      <locale lang="en" href="decks/standard-playing/locales/deck.en.xml"/>
    </locales>
    <images basePath="assets/img/playing/"/>
  </deck>

  <deck id="lenormand" type="oracle" version="1.0" status="draft">
    <name>Lenormand Oracle</name>
    <description>36-card fortune-telling deck</description>
    <cardCount>36</cardCount>
    <structure href="decks/lenormand/structure.xml"/>
    <metadata href="decks/lenormand/metadata.xml"/>
    <locales>
      <locale lang="en" href="decks/lenormand/locales/deck.en.xml"/>
    </locales>
    <images basePath="assets/img/lenormand/"/>
  </deck>

  <deck id="zen" type="tarot" version="1.0">
    <name>Zen Deck</name>
    <description>18 major cards (Mu, Kuoan's ten ox-herding pictures, seven transmission scenes) and 75 minor cards in five suits of the elements, with Dongshan's Five Ranks as court cards</description>
    <cardCount>93</cardCount>
    <structure href="decks/zen/structure.xml"/>
    <metadata href="decks/zen/metadata.xml"/>
    <locales>
      <locale lang="en" href="decks/zen/locales/deck.en.xml"/>
    </locales>
    <images basePath="assets/img/zen/"/>
  </deck>

  <deck id="pessimistic" type="tarot" version="1.0">
    <name>Pessimist Deck</name>
    <description>16 major cards in three movements, from Silenus to Zapffe's last Messiah, and 56 minor cards in four suits of Zapffe's mechanisms, with the four ages of life as court cards</description>
    <cardCount>72</cardCount>
    <structure href="decks/pessimistic/structure.xml"/>
    <metadata href="decks/pessimistic/metadata.xml"/>
    <locales>
      <locale lang="en" href="decks/pessimistic/locales/deck.en.xml"/>
    </locales>
    <images basePath="assets/img/pessimistic/"/>
  </deck>
</decks>
