=== trondarild/tarot-deck/data/schemas/metadata.dtd
<!ELEMENT metadata (card+)>
<!ATTLIST metadata deck CDATA #REQUIRED>

<!ELEMENT card (core, tarot?, playing?, oracle?, custom?)>
<!ATTLIST card id CDATA #REQUIRED>

<!ELEMENT core (displayNumber, sortOrder)>
<!ELEMENT displayNumber (#PCDATA)>
<!ELEMENT sortOrder (#PCDATA)>

<!ELEMENT tarot (arcana, hebrew?, astrology?, kabbalah?)>
<!ELEMENT arcana (#PCDATA)>
<!ELEMENT hebrew (#PCDATA)>
<!ELEMENT astrology (sign?, element?)>
<!ELEMENT sign (#PCDATA)>
<!ELEMENT element (#PCDATA)>
<!ELEMENT kabbalah (path?, sephiroth?)>
<!ELEMENT path (#PCDATA)>
<!ELEMENT sephiroth EMPTY>
<!ATTLIST sephiroth
  from CDATA #IMPLIED
  to CDATA #IMPLIED>

<!ELEMENT playing (suit, rank, value?, faceCard?)>
<!ELEMENT suit (#PCDATA)>
<!ELEMENT rank (#PCDATA)>
<!ELEMENT value (#PCDATA)>
<!ELEMENT faceCard (#PCDATA)>

<!ELEMENT oracle (number, symbol?)>
<!ELEMENT number (#PCDATA)>
<!ELEMENT symbol (#PCDATA)>

<!ELEMENT custom (attribute*)>
<!ELEMENT attribute EMPTY>
<!ATTLIST attribute
  name CDATA #REQUIRED
  value CDATA #REQUIRED>

=== trondarild/tarot-deck/data/decks/standard-playing/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE metadata SYSTEM "../../schemas/metadata.dtd">
<metadata deck="standard-playing">
  <card id="h01"><core><displayNumber>A</displayNumber><sortOrder>1</sortOrder></core><playing><suit>hearts</suit><rank>ace</rank><value>1</value><faceCard>false</faceCard></playing></card>
  <card id="h11"><core><displayNumber>J</displayNumber><sortOrder>11</sortOrder></core><playing><suit>hearts</suit><rank>jack</rank><value>10</value><faceCard>true</faceCard></playing></card>
  <card id="h12"><core><displayNumber>Q</displayNumber><sortOrder>12</sortOrder></core><playing><suit>hearts</suit><rank>queen</rank><value>10</value><faceCard>true</faceCard></playing></card>
  <card id="h13"><core><displayNumber>K</displayNumber><sortOrder>13</sortOrder></core><playing><suit>hearts</suit><rank>king</rank><value>10</value><faceCard>true</faceCard></playing></card>
</metadata>

=== trondarild/tarot-deck/data/decks/lenormand/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE metadata SYSTEM "../../schemas/metadata.dtd">
<metadata deck="lenormand">
  <card id="01"><core><displayNumber>1</displayNumber><sortOrder>1</sortOrder></core><oracle><number>1</number><symbol>🚴</symbol></oracle></card>
  <card id="02"><core><displayNumber>2</displayNumber><sortOrder>2</sortOrder></core><oracle><number>2</number><symbol>🍀</symbol></oracle></card>
  <card id="03"><core><displayNumber>3</displayNumber><sortOrder>3</sortOrder></core><oracle><number>3</number><symbol>🚢</symbol></oracle></card>
</metadata>

=== trondarild/tarot-deck/data/decks/pessimistic/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE metadata SYSTEM "../../schemas/metadata.dtd">
<metadata deck="pessimistic">
  <card id="00"><core><displayNumber>0</displayNumber><sortOrder>1</sortOrder></core><tarot><arcana>major</arcana></tarot></card>
  <card id="01"><core><displayNumber>I</displayNumber><sortOrder>2</sortOrder></core><tarot><arcana>major</arcana></tarot></card>
  <card id="02"><core><displayNumber>II</displayNumber><sortOrder>3</sortOrder></core><tarot><arcana>major</arcana></tarot></card>
  <card id="03"><core><displayNumber>III</displayNumber><sortOrder>4</sortOrder></core><tarot><arcana>major</arcana></tarot></card>
  <card id="04"><core><displayNumber>IV</displayNumber><sortOrder>5</sortOrder></core><tarot><arcana>major</arcana></tarot></card>
  <card id="05"><core><displayNumber>V</displayNumber><sortOrder>6</sortOrder></core><tarot><arcana>major</arcana></tarot></card>
  <card id="06"><core><displayNumber>VI</displayNumber><sortOrder>7</sortOrder></core><tarot><arcana>major</arcana></tarot></card>
  <card id="07"><core><displayNumber>VII</displayNumber><sortOrder>8</sortOrder></core><tarot><arcana>major</arcana></tarot></card>
  <card id="08"><core><displayNumber>VIII</displayNumber><sortOrder>9</sortOrder></core><tarot><arcana>major</arcana></tarot></card>
  <card id="09"><core><displayNumber>IX</displayNumber><sortOrder>10</sortOrder></core><tarot><arcana>major</arcana></tarot></card>
  <card id="10"><core><displayNumber>X</displayNumber><sortOrder>11</sortOrder></core><tarot><arcana>major</arcana></tarot></card>
  <card id="11"><core><displayNumber>XI</displayNumber><sortOrder>12</sortOrder></core><tarot><arcana>major</arcana></tarot></card>
  <card id="12"><core><displayNumber>XII</displayNumber><sortOrder>13</sortOrder></core><tarot><arcana>major</arcana></tarot></card>
  <card id="13"><core><displayNumber>XIII</displayNumber><sortOrder>14</sortOrder></core><tarot><arcana>major</arcana></tarot></card>
  <card id="14"><core><displayNumber>XIV</displayNumber><sortOrder>15</sortOrder></core><tarot><arcana>major</arcana></tarot></card>
  <card id="15"><core><displayNumber>XV</displayNumber><sortOrder>16</sortOrder></core><tarot><arcana>major</arcana></tarot></card>
  <card id="is01"><core><displayNumber>1</displayNumber><sortOrder>17</sortOrder></core><tarot><arcana>minor</arcana></tarot></card>
  <card id="is02"><core><displayNumber>2</displayNumber><sortOrder>18</sortOrder></core><tarot><arcana>minor</arcana></tarot></card>
  <card id="is03"><core><displayNumber>3</displayNumber><sortOrder>19</sortOrder></core><tarot><arcana>minor</arcana></tarot></card>
  <card id="is04"><core><displayNumber>4</displayNumber><sortOrder>20</sortOrder></core><tarot><arcana>minor</arcana></tarot></card>
  <card id="is05"><core><displayNumber>5</displayNumber><sortOrder>21</sortOrder></core><tarot><arcana>minor</arcana></tarot></card>
  <card id="is06"><core><displayNumber>6</displayNumber><sortOrder>22</sortOrder></core><tarot><arcana>minor</arcana></tarot></card>
  <card id="is07"><core><displayNumber>7</displayNumber><sortOrder>23</sortOrder></core><tarot><arcana>minor</arcana></tarot></card>
  <card id="is08"><core><displayNumber>8</displayNumber><sortOrder>24</sortOrder></core><tarot><arcana>minor</arcana></tarot></card>
  <card id="is09"><core><displayNumber>9</displayNumber><sortOrder>25</sortOrder></core><tarot><arcana>minor</arcana></tarot></card>
  <card id="is10"><core><displayNumber>10</displayNumber><sortOrder>26</sortOrder></core><tarot><arcana>minor</arcana></tarot></card>
  <card id="is11"><core><displayNumber>Child</displayNumber><sortOrder>27</sortOrder></core><tarot><arcana>minor</arcana></tarot></card>
  <card id="is12"><core><displayNumber>Youth</displayNumber><sortOrder>28</sortOrder></core><tarot><arcana>minor</arcana></tarot></card>
  <card id="is13"><core><displayNumber>Adult</displayNumber><sortOrder>29</sortOrder></core><tarot><arcana>minor</arcana></tarot></card>
  <card id="is14"><core><displayNumber>Elder</displayNumber><sortOrder>30</sortOrder></core><tarot><arcana>minor</arcana></tarot></card>
  <card id="an01"><core><displayNumber>1</displayNumber><sortOrder>31</sortOrder></core><tarot><arcana>minor</arcana></tarot></card>
  <card id="an02"><core><displayNumber>2</displayNumber><sortOrder>32</sortOrder></core><tarot><arcana>minor</arcana></tarot></card>
  <card id="an03"><core><displayNumber>3</displayNumber><sortOrder>33</sortOrder></core><tarot><arcana>minor</arcana></tarot></card>
  <card id="an04"><core><displayNumber>4</displayNumber><sortOrder>34</sortOrder></core><tarot><arcana>minor</arcana></tarot></card>
  <card id="an05"><core><displayNumber>5</displayNumber><sortOrder>35</sortOrder></core><tarot><arcana>minor</arcana></tarot></card>
  <card id="an06"><core><displayNumber>6</displayNumber><sortOrder>36</sortOrder></core><tarot><arcana>minor</arcana></tarot></card>
  <card id="an07"><core><displayNumber>7</displayNumber><sortOrder>37</sortOrder></core><tarot><arcana>minor</arcana></tarot></card>
  <card id="an08"><core><displayNumber>8</displayNumber><sortOrder>38</sortOrder></core><tarot><arcana>minor</arcana></tarot></card>
  <card id="an09"><core><displayNumber>9</displayNumber><sortOrder>39</sortOrder></core><tarot><arcana>minor</arcana></tarot></card>
  <card id="an10"><core><displayNumber>10</displayNumber><sortOrder>40</sortOrder></core><tarot><arcana>minor</arcana></tarot></card>
  <card id="an11"><core><displayNumber>Child</displayNumber><sortOrder>41</sortOrder></core><tarot><arcana>minor</arcana></tarot></card>
  <card id="an12"><core><displayNumber>Youth</displayNumber><sortOrder>42</sortOrder></core><tarot><arcana>minor</arcana></tarot></card>
  <card id="an13"><core><displayNumber>Adult</displayNumber><sortOrder>43</sortOrder></core><tarot><arcana>minor</arcana></tarot></card>
  <card id="an14"><core><displayNumber>Elder</displayNumber><sortOrder>44</sortOrder></core><tarot><arcana>minor</arcana></tarot></card>
  <card id="di01"><core><displayNumber>1</displayNumber><sortOrder>45</sortOrder></core><tarot><arcana>minor</arcana></tarot></card>
  <card id="di02"><core><displayNumber>2</displayNumber><sortOrder>46</sortOrder></core><tarot><arcana>minor</arcana></tarot></card>
  <card id="di03"><core><displayNumber>3</displayNumber><sortOrder>47</sortOrder></core><tarot><arcana>minor</arcana></tarot></card>
  <card id="di04"><core><displayNumber>4</displayNumber><sortOrder>48</sortOrder></core><tarot><arcana>minor</arcana></tarot></card>
  <card id="di05"><core><displayNumber>5</displayNumber><sortOrder>49</sortOrder></core><tarot><arcana>minor</arcana></tarot></card>
  <card id="di06"><core><displayNumber>6</displayNumber><sortOrder>50</sortOrder></core><tarot><arcana>minor</arcana></tarot></card>
  <card id="di07"><core><displayNumber>7</displayNumber><sortOrder>51</sortOrder></core><tarot><arcana>minor</arcana></tarot></card>
  <card id="di08"><core><displayNumber>8</displayNumber><sortOrder>52</sortOrder></core><tarot><arcana>minor</arcana></tarot></card>
  <card id="di09"><core><displayNumber>9</displayNumber><sortOrder>53</sortOrder></core><tarot><arcana>minor</arcana></tarot></card>
  <card id="di10"><core><displayNumber>10</displayNumber><sortOrder>54</sortOrder></core><tarot><arcana>minor</arcana></tarot></card>
  <card id="di11"><core><displayNumber>Child</displayNumber><sortOrder>55</sortOrder></core><tarot><arcana>minor</arcana></tarot></card>
  <card id="di12"><core><displayNumber>Youth</displayNumber><sortOrder>56</sortOrder></core><tarot><arcana>minor</arcana></tarot></card>
  <card id="di13"><core><displayNumber>Adult</displayNumber><sortOrder>57</sortOrder></core><tarot><arcana>minor</arcana></tarot></card>
  <card id="di14"><core><displayNumber>Elder</displayNumber><sortOrder>58</sortOrder></core><tarot><arcana>minor</arcana></tarot></card>
  <card id="su01"><core><displayNumber>1</displayNumber><sortOrder>59</sortOrder></core><tarot><arcana>minor</arcana></tarot></card>
  <card id="su02"><core><displayNumber>2</displayNumber><sortOrder>60</sortOrder></core><tarot><arcana>minor</arcana></tarot></card>
  <card id="su03"><core><displayNumber>3</displayNumber><sortOrder>61</sortOrder></core><tarot><arcana>minor</arcana></tarot></card>
  <card id="su04"><core><displayNumber>4</displayNumber><sortOrder>62</sortOrder></core><tarot><arcana>minor</arcana></tarot></card>
  <card id="su05"><core><displayNumber>5</displayNumber><sortOrder>63</sortOrder></core><tarot><arcana>minor</arcana></tarot></card>
  <card id="su06"><core><displayNumber>6</displayNumber><sortOrder>64</sortOrder></core><tarot><arcana>minor</arcana></tarot></card>
  <card id="su07"><core><displayNumber>7</displayNumber><sortOrder>65</sortOrder></core><tarot><arcana>minor</arcana></tarot></card>
  <card id="su08"><core><displayNumber>8</displayNumber><sortOrder>66</sortOrder></core><tarot><arcana>minor</arcana></tarot></card>
  <card id="su09"><core><displayNumber>9</displayNumber><sortOrder>67</sortOrder></core><tarot><arcana>minor</arcana></tarot></card>
  <card id="su10"><core><displayNumber>10</displayNumber><sortOrder>68</sortOrder></core><tarot><arcana>minor</arcana></tarot></card>
  <card id="su11"><core><displayNumber>Child</displayNumber><sortOrder>69</sortOrder></core><tarot><arcana>minor</arcana></tarot></card>
  <card id="su12"><core><displayNumber>Youth</displayNumber><sortOrder>70</sortOrder></core><tarot><arcana>minor</arcana></tarot></card>
  <card id="su13"><core><displayNumber>Adult</displayNumber><sortOrder>71</sortOrder></core><tarot><arcana>minor</arcana></tarot></card>
  <card id="su14"><core><displayNumber>Elder</displayNumber><sortOrder>72</sortOrder></core><tarot><arcana>minor</arcana></tarot></card>
</metadata>
